name: Automatyczny Monitoring Jeziorska

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    - name: Pobranie kodu repozytorium
      uses: actions/checkout@v4

    - name: Konfiguracja Pythona
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalacja biblioteki Requests
      run: pip install requests

    - name: Uruchomienie skrobaka danych
      run: python pobierz_dane.py

    - name: Zapisanie zmian w pliku JSON
      run: |
        git config --global user.name "JeziorskoBot"
        git config --global user.email "bot@jeziorsko.internal"
        git add dane.json
        git commit -m "Automatyczna aktualizacja bazy JSON" || echo "Brak zmian"
        git push
